### ISSUE TITLE
为指令增加权限节点检查

### ISSUE THREAD

**Issue by balugaq** [balugaq/SlimefunCoreProtect#1]
### 检查项目

- [x] 你已经寻找过[已知问题列表](https://github.com/ytdd9527/SlimefunCoreProtect/issues)，且没有找到相同的建议

### 提议动机

便于玩家自行使用

### 提议内容

新增 permissions.yml

```yaml
commands:
  inspect:
    basePermission: op # op / none 
    extraPermission: # 需要全部满足
      - a_example_nde
      - same
  # 其他权限节点

```
